import { SelectItemsType } from "../components/Select";

export const exercisesCategories: SelectItemsType[] = [
     {
          text: 'Costas',
          value: 0
     },
     {
          text: 'Ombro',
          value: 1
     },
     {
          text: 'Bìceps',
          value: 2
     },
     {
          text: 'Tríceps',
          value: 3
     },
     {
          text: 'Peito',
          value: 4
     },
]

export const exercisesList = [
     { "id": 1, "label": "Flexões", "day": 3 },
     { "id": 2, "label": "Barra fixa", "day": 5 },
     { "id": 3, "label": "Agachamentos", "day": 2 },
     { "id": 4, "label": "Avanços", "day": 7 },
     { "id": 5, "label": "Levantamento terra", "day": 1 },
     { "id": 6, "label": "Prancha", "day": 4 },
     { "id": 7, "label": "Burpees", "day": 6 },
     { "id": 8, "label": "Abdominais", "day": 2 },
     { "id": 9, "label": "Polichinelos", "day": 7 },
     { "id": 10, "label": "Curl de bíceps", "day": 3 },
     { "id": 11, "label": "Mergulhos de tríceps", "day": 5 },
     { "id": 12, "label": "Escaladores", "day": 1 },
     { "id": 13, "label": "Supino", "day": 4 },
     { "id": 14, "label": "Leg Press", "day": 6 },
     { "id": 15, "label": "Elevação de panturrilha", "day": 7 },
     { "id": 16, "label": "Corrida", "day": 3 },
     { "id": 17, "label": "Remo", "day": 5 },
     { "id": 18, "label": "Flexões diamante", "day": 2 },
     { "id": 19, "label": "Rosca direta", "day": 7 },
     { "id": 20, "label": "Agachamento búlgaro", "day": 1 },
     { "id": 21, "label": "Prancha lateral", "day": 4 },
     { "id": 22, "label": "Agachamento com salto", "day": 6 },
     { "id": 23, "label": "Bicicleta", "day": 2 },
     { "id": 24, "label": "Pular corda", "day": 7 },
     { "id": 25, "label": "Flexões declinadas", "day": 3 },
     { "id": 26, "label": "Puxada frontal", "day": 5 },
     { "id": 27, "label": "Afundo", "day": 1 },
     { "id": 28, "label": "Super-homem", "day": 4 },
     { "id": 29, "label": "Corrida estacionária", "day": 6 },
     { "id": 30, "label": "Rosca martelo", "day": 3 },
     { "id": 31, "label": "Prancha com elevação do quadril", "day": 5 },
     { "id": 32, "label": "Flexões em T", "day": 2 },
     { "id": 33, "label": "Cadeira romana", "day": 7 },
     { "id": 34, "label": "Stiff", "day": 1 },
     { "id": 35, "label": "Abdominais cruzados", "day": 4 },
     { "id": 36, "label": "Salto com escada", "day": 6 },
     { "id": 37, "label": "Rosca scott", "day": 3 },
     { "id": 38, "label": "Mountain climbers", "day": 5 },
     { "id": 39, "label": "Polichinelo cruzado", "day": 2 },
     { "id": 40, "label": "Pular corda", "day": 7 },
     { "id": 41, "label": "Flexões com bola", "day": 3 },
     { "id": 42, "label": "Elevação lateral", "day": 5 },
     { "id": 43, "label": "Agachamento sumô", "day": 1 },
     { "id": 44, "label": "Prancha com rotação", "day": 4 },
     { "id": 45, "label": "Salto com banco", "day": 6 },
     { "id": 46, "label": "Rosca arnold", "day": 3 },
     { "id": 47, "label": "Abdominal oblíquo", "day": 5 },
     { "id": 48, "label": "Extensão de quadril", "day": 2 },
     { "id": 49, "label": "Bíceps na máquina", "day": 7 },
     { "id": 50, "label": "Pistol squat", "day": 1 },
     { "id": 51, "label": "Elevação frontal", "day": 4 },
     { "id": 52, "label": "Afundo com salto", "day": 6 },
     { "id": 53, "label": "Rosca 21", "day": 3 },
     { "id": 54, "label": "Flexões com pés elevados", "day": 5 },
     { "id": 55, "label": "Afundo lateral", "day": 2 },
     { "id": 56, "label": "Gêmeos em pé", "day": 7 },
     { "id": 57, "label": "Levantamento terra sumô", "day": 3 },
     { "id": 58, "label": "Elevação lateral com halter", "day": 5 },
     { "id": 59, "label": "Passada na caixa", "day": 1 },
     { "id": 60, "label": "Ponte", "day": 4 },
     { "id": 61, "label": "Agachamento frontal", "day": 6 },
     { "id": 62, "label": "Rosca inversa", "day": 3 },
     { "id": 63, "label": "Elevação de pernas", "day": 5 },
     { "id": 64, "label": "Prancha com braço estendido", "day": 2 },
     { "id": 65, "label": "Flexões inclinadas", "day": 7 },
     { "id": 66, "label": "Bíceps na barra fixa", "day": 3 },
]